#:kivy 1.10.1

<Playground>
    canvas.before:
        Rectangle:
            pos: self.pos
            size: 414, 736
            source: 'img/background.png'
    
    doodle: doodle_id
    Doodle:
        id: doodle_id
        size: 75, 75
        doodle_img: doodle_img_id
        Image:
            id: doodle_img_id
            pos: self.pos
            size: 75, 75
            source: 'img/doodle.png'
